### ISSUE TITLE
Transferring File to LaTex

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#1]
@ejmaginn Would you like me to transfer our google doc to LaTex and upload to GitHub? I was not sure if we wanted to keep working with the google doc until it is a bit more polished. The main advantage of moving it to LaTex and uploading to GitHub now is the issue tracking and version control.  I just didn't want to make the change now if people are still working on the google doc and/or already working on transferring the document. Also, whenever we do make the change, there is a journal template that we should follow.

**Comment by ejmaginn** [comment]
Richard,

If you are willing to take care of the GitHub management, that would be great. I think it is best to get this off of the Google Doc. Will you communicate with the rest of the team? We need to establish a date when this will be ready. For me, late October will be the earliest. I can back to campus and have been buried with other things.

Thanks,
Ed

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn

**Comment by ramess101** [comment]
Yeah, I will take care of converting it to LaTex tomorrow. To simplify things, could you add me as a collaborator to the repository? Also, if you add the other members as collaborators (their GitHub accounts are on the google doc) then it will be easier for me to contact them via GitHub.
