### ISSUE TITLE
LiveCoMS Reviewers

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#11]
@ejmaginn @drroe @jrelliottoh @dcarls0n 

If you have a strong preference for who I should list on LiveCoMS as "Suggested reviewers" and "Reviewers to avoid", please let me know by the end of the day.

**Comment by ramess101** [comment]
Currently I have listed:

Suggested Reviewers:

Jadran Vrabec
Richard Rowley

Reviewers to avoid

The NIST reviewers (Dan Siderius and Arno Laesecke)

**Comment by ejmaginn** [comment]
Suggestions for suggested reviewers (please feel free to veto / ignore): Peter Cummings, Ioannis Economou, Jadran Vrabec, Rajesh Khare

I don't have any people I would exclude.

**Comment by ramess101** [comment]
@ejmaginn 

Good, those are some good reviewers to include.
