### ISSUE TITLE
Clean up entry page?

### ISSUE THREAD

**Issue by davidlmobley** [ejmaginn/TransportCheckList#12]
@ramess101 - got your submission, clicked through to the repo. The first thing I noticed was that there are a lot of files here and it's really hard to see which is actually your manuscript. The first one I clicked on was https://github.com/ejmaginn/TransportCheckList/blob/master/EMD_diffusivity_viscosity.pdf which does NOT seem to be the one you want public-facing.

I suggest:
a) Updating your README.md to say what this is, and which document(s) are the ones for your paper, and:
b) Moving old/outdated/unused files out of the repo or to subdirectories where they are clearly labeled as not intended for use

Remember, people will click the link in the paper and it will lead them to your repo, so you want to end up with it being clear what they should do once they get here.

See https://github.com/dmzuckerman/Sampling-Uncertainty and the README at the bottom there for a minimal example of what you might want, though they probably also need to say what document provides the latest version of the paper.

**Comment by ramess101** [comment]
@davidlmobley 

Thanks David. I completely agree. This was on my list of things to do for a while now but I probably won't get around to until after the 20th Symposium next week.

**Comment by ramess101** [comment]
The README file could still be a little more useful. But I think the repository is at least less cluttered now.
