### ISSUE TITLE
Acknowledgments

### ISSUE THREAD

**Issue by davidlmobley** [ejmaginn/TransportCheckList#13]
The PDF has an acknowledgment of financial support for DMZ, but no author has those initials.

**Comment by ramess101** [comment]
@drroe 

Was this supposed to be your financial support statement? Should this say DRR? No one else would have funding from an NIH grant.

Or is this a mistake entirely? I noticed that the exact same statement is found in the other LiveCoMS best practices guide that you contributed to (https://github.com/dmzuckerman/Sampling-Uncertainty/blob/master/main.pdf) where Daniel M. Zuckerman (DMZ) was an author. So maybe this got copied over by mistake.

**Comment by drroe** [comment]
I definitely didn't add it (I don't get grants from the NIH since I _work_ for the NIH :smiley:). Seems like a copy/paste error and can be removed.
