### ISSUE TITLE
Equations 4 and 7

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#16]
@ejmaginn 

Are we missing the double sums over "i" and "j" in Equations 4 and 7? We have double summations in the corresponding Einstein relations (Equations 6 and 8). Without the double sums, the subscripts i and j for tau^os are meaningless. So I think we simply omitted the double sum, but I wanted to verify with you first.

![image](https://user-images.githubusercontent.com/23408516/44815730-93a3c980-ab9d-11e8-8508-3f593510eac2.png)
![image](https://user-images.githubusercontent.com/23408516/44815741-9a324100-ab9d-11e8-89ac-622ce205a415.png)

![image](https://user-images.githubusercontent.com/23408516/44815757-a5856c80-ab9d-11e8-843b-50a9f6442827.png)

**Comment by ejmaginn** [comment]
@ramess101 I think you are right. The < > average implies the sum but to be consistent with the other equations we should include it.

**Comment by ramess101** [comment]
@ejmaginn 

Yeah, that makes sense. For consistency, I have updated Equations 4 and 7:

![image](https://user-images.githubusercontent.com/23408516/44853987-9eee0800-ac24-11e8-9e82-527405b42a9a.png)

![image](https://user-images.githubusercontent.com/23408516/44854010-aad9ca00-ac24-11e8-96ad-6975222d4cab.png)
