### ISSUE TITLE
Conclusions

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#17]
@ejmaginn @drroe @jrelliottoh @dcarls0n 

After implementing the recent changes and reading the article once again, I felt like our conclusions section needed some significant revision. Specifically, some of the recommendations weren't exactly consistent with the main text. The partitioning of topics was also different from the text, as there were only conclusions for diffusivity and viscosity, but not for "general transport." This made the diffusivity and viscosity paragraphs too long and unnecessarily redundant. I have made considerable modifications to the conclusions such that there are now "general transport" conclusions followed by (shorter) diffusivity and viscosity conclusions.

Before we resubmit, I would appreciate if everyone could re-read the conclusions section to make sure it looks good or to provide changes. I would like to resubmit by this weekend, so please let me know if you plan on reviewing the conclusions and if that timeline will not work for you.

**Comment by ejmaginn** [comment]
@ramess101 Thanks - I will take a look this evening.

**Comment by ramess101** [comment]
@ejmaginn 

Sorry for pestering you, I just wanted to check on your status. 

I hope you have a good labor day!

**Comment by ramess101** [comment]
@ejmaginn 

Thanks Ed. I think we are ready to resubmit then.

Regarding Eqn 4, it should have a double summation (see Issue #16). If your version does not have that, make sure you have pulled the changes.
