### ISSUE TITLE
Work plan

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#2]
@ejmaginn @drroe 

Happy holidays! I think we should make a work plan for when/what/how much each of us is going to contribute. For example, I am going to start working on this manuscript again. Specifically, I am going to bulk up the Green-Kubo and Einstein discussion for viscosity. I will have this completed by the end of the calendar year. After I have finished my changes it would be someone else's turn to look over the document and see what portion they think is lacking. Does that sound reasonable?

**Comment by ejmaginn** [comment]
Richard,

That sounds like a good plan. I also added Richard as a collaborator. I can take a crack at this when you are finished.

Let me know if you receive this email as I am unsure if this list works.

Ed


Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn

**Comment by ramess101** [comment]
@ejmaginn 

I did receive the email. OK, I will let you know when I am satisfied with what I have. I also think it would be good to have a video call to regroup since it has been a while.

**Comment by drroe** [comment]
Apologies for the delay, I've been traveling. I will look over the update document ASAP.

**Comment by ramess101** [comment]
@drroe 

OK, great. I will finish my changes by the end of the day. I think it will be easiest if we are not all making changes simultaneously. Although GitHub can keep track of our changes, I think taking turns will avoid merge conflicts that might be prevalent when making significant changes.

So after I finish today, who wants to be next? @ejmaginn @drroe @jrelliottoh?

**Comment by ramess101** [comment]
@ejmaginn @drroe @jrelliottoh 

I have finished my changes. Whoever wants to pick it up next, post a comment here.

Note that I have focused primarily on the content and not as much on the layout. We will probably want to discuss the sectioning and the overall flow of the document once we are satisfied with the content.

**Comment by ejmaginn** [comment]
I can start in earnest Tuesday of next week - I am traveling and have a proposal I am trying to finish this week. So if someone can step in now that would be great. Otherwise, I will start on this Tuesday Jan 2.

Ed

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn

**Comment by jrelliottoh** [comment]
I will look at it this afternoon. (1/4)JRE


    On Thursday, December 28, 2017, 12:33:46 PM EST, Richard Messerly <notifications@github.com> wrote:  
 
 
@drroe

OK, great. I will finish my changes by the end of the day. I think it will be easiest if we are not all making changes simultaneously. Although GitHub can keep track of our changes, I think taking turns will avoid merge conflicts that might be prevalent when making significant changes.

So after I finish today, who wants to be next? @ejmaginn @drroe @jrelliottoh?

**Comment by ramess101** [comment]
@ejmaginn  @drroe @jrelliottoh @dcarls0n

Since the school year should be ending in a few weeks, I thought we should try to pick this back up. I know that one other group is about to submit their best practices to LiveComs, so we should probably try to have something done in a month or so.

We had talked about having a system where we take turns looking at the document. From the best I can tell, @ejmaginn and @jrelliottoh were going to review the article on January 2nd and 4th, respectively. But it doesn't look like any changes were made. Did you have some edits/comments? Who would be willing to look at the document in the coming week or so?

**Comment by ejmaginn** [comment]
Richard,

Thanks for (gently) nudging us. I have been thinking about this and feeling guilty for not doing much. I am waiting until a wave of proposals gets submitted before picking this up again. 

I can work on this after April 16 but won’t be able to devote much time before then. If someone would like to take a crack at it between now and then, I can pick it up at that time.

Ed

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe

**Comment by ramess101** [comment]
@ejmaginn 

I am glad that it came off as a gentle nudge. I know you all have a lot going on, and are especially busy during the semester. I will also be more available in two weeks, working on submitting a publication right now.  My plan is to focus on finalizing this document from mid April till late May (hopefully it is done by then).

@dcarls0n reached out to me yesterday. I asked him to review the manuscript in the next two weeks to point out sections that are not clear and/or need to be reorganized. 

So in two weeks, I think it would be good if at least @ejmaginn, @dcarls0n and myself discussed what improvements need to be made to the document. Maybe the three of us could have a video conference? I think the manuscript is not short on content, but currently lacks a good narrative and structure.

@drroe and @jrelliottoh when do you think you would be able to work on or discuss the manuscript?

**Comment by ejmaginn** [comment]
I am happy to work on something after April 16.


Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe

**Comment by ejmaginn** [comment]
Richard,
Thanks. Please tell me when you are finished and I am happy to take the next crack at it. Just finished my proposal today!

Ed

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe

**Comment by ramess101** [comment]
@ejmaginn 

Alright, I will let you know when I finish. I do think a brief video call sometime this week would be helpful even if it is before you start working on it. Let me know what you think.

**Comment by ejmaginn** [comment]
Good idea. I am free Tuesday afternoon from 2-5 pm EDT. I don’t have much other time during business hours the rest of the week (!) but could talk outside business hours if we want. Thursday evening April 19 is best for me.

Ed

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe

**Comment by ramess101** [comment]
@ejmaginn 

Alright, @dcarls0n said that he has a meeting at 3 EDT, and I have a meeting at 4 EDT, so 2 EDT would work best for us tomorrow. I do not think it will take more than 30-45 minutes. Would google hangouts work for you? If so, what email should I send the link to?

**Comment by ejmaginn** [comment]
OK - I have sometimes had trouble with this but you can try ed@nd.edu <mailto:ed@nd.edu> - this should work. If not, try my gmail account ejmaginn@gmail.com <mailto:ejmagin@gmail.com>


Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe

**Comment by ramess101** [comment]
@ejmaginn  @dcarls0n 

OK, I will send the link a few minutes before our meeting time (tomorrow at 12 MT/2 ET).

**Comment by ramess101** [comment]
@ejmaginn @dcarls0n 

Alright, EMD_diffusivity_viscosity_restructured now contains all of my modifications. I think this structure is a lot better, but we should discuss this tomorrow. If you could take a quick glance before tomorrow to compare the old and new manuscript formats that would be helpful.

**Comment by ramess101** [comment]
@ejmaginn @dcarls0n 

Here is the link:

https://hangouts.google.com/call/V12I-HqQ1cN7EXJz_stmAAEE
