### ISSUE TITLE
ASAP Production

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#23]
@ejmaginn @drroe @jrelliottoh @dcarls0n 

Before our manuscript can enter the ASAP production stage, we need to address a few issues.

1) Update the template to the latest version on GitHub
2) Create a representative cover image
3) Provide ORCID IDs
4) Remove PMIDs
5) Consistent journal abbreviations

I will take care of 1, 4, and 5. I have already updated the template version and will push those changes soon. I will go through the references to remove PMIDs shortly. I thought the journal abbreviations issue had already been resolved, but I will go through that again. 

So the only two that I need some help on are numbers 2 and 3. For 3, Michael already has an ORCID ID for myself and Ed, so if @drroe @jrelliottoh @dcarls0n have an ORCID ID, please let me know. For 2, does anyone feel like they could make a good cover image? Here is Michael's description regarding this image:

> Note that the focus should be more on visual communication than a table of contents figure, and should be high resolution (at least 1200 wide, wider than high); it will appear on the web page, and in any social media; take a look at existing articles and blogs and see how the image is used.

I admit that I am not very good at making eye-catching cover images. Most of mine are just a graph with some arrows connecting methods and results. We would like to get this done in the next few days if possible, so please let me know.

**Comment by ejmaginn** [comment]
I work with a talented graphic artist who can make something if you can help provide a concept. What would we like this to look like?

**Comment by drroe** [comment]
Hi,

My ORCID is https://orcid.org/0000-0002-5834-2447. I'm not super great with graphics but I'll see if anyone in the lab has any good ideas.

**Comment by ramess101** [comment]
@ejmaginn 

That would be great. I think we have a few options. With my limited artistic abilities, I would think of something that depicts a molecular system with vectors denoting the transport of mass and momentum.

**Comment by ramess101** [comment]
@jrelliottoh 

From a quick search, I assume this is your ORCID: https://orcid.org/0000-0002-1159-4786

**Comment by dcarls0n** [comment]
My ORCID ID:
https://orcid.org/0000-0002-6610-414X

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ramess101** [comment]
@ejmaginn @drroe @dcarls0n @jrelliottoh 

I received some clarification from Michael regarding the cover image. It does not need to be a "table of contents image" or a "visual abstract." This is really just supposed to catch someone's attention and be related to our topic. 

So I think a pretty simple design would be something that denotes viscosity (e.g., molasses, honey, or just flowing water) and/or diffusion (e.g., a beaker with some dye dispersing) and then have a magnifying glass or just some way to zoom in and show a picture of molecules. No math, no graphs, no Green-Kubo equation, no simulations. Just showing that we get macroscopic transport properties from molecular detail.

**Comment by ramess101** [comment]
@ejmaginn @drroe @dcarls0n @jrelliottoh 

I just wanted to let everyone know that the only thing LiveCoMS is waiting on for publication is the cover image. @ejmaginn has any progress been made in that area? Does anyone else have an idea or the interest/ability to make this?

**Comment by ejmaginn** [comment]
My bad. I dropped the ball but I have just asked for help with this and will let you know what I find out asap.

**Comment by ramess101** [comment]
Alright not a problem. We should just try to get this figured out soon. So
let us know ASAP if you will not be able to make the image.

**Comment by ejmaginn** [comment]
OK I imagine it will be after Thanksgiving but hopefully not long after.

**Comment by jrelliottoh** [comment]
FYI, I made a mockup of what is in my mind about a wheel bearing since I never heard what you were actually drawing up.JRE

    On Monday, November 19, 2018, 10:49:07 PM EST, Edward Maginn <notifications@github.com> wrote:  
 
 
OK I imagine it will be after Thanksgiving but hopefully not long after.

**Comment by ramess101** [comment]
I don’t think the group ever heard about your wheel bearing idea. It’s
nowhere on the thread.

**Comment by ejmaginn** [comment]
I should have it early next week. I am going to take a photo of a beaker with dye in it and we will mash it up with some molecule images. Does anyone have a preference for which molecules to show? And if so, do you have *.xyz of *.pdb files of them? Otherwise, I will make something up.

**Comment by ramess101** [comment]
That sounds good to me. I don't have any preference for which molecules you depict.

**Comment by ejmaginn** [comment]
Guys, attached is a (admittedly not great) image trying to show the concept of diffusion. I took the picture myself and a colleague did some photoshopping. She thinks she can do better with more work - but what does everyone think of this at least for now?
![transport-checklist-image](https://user-images.githubusercontent.com/9609821/49106621-a9cf2d80-f251-11e8-8dde-2115c0a735dc.png)

**Comment by ramess101** [comment]
@ejmaginn 

This is basically what I envisioned. My three (minor) suggestions would be to:

1) Zoom out so that you can see the entire beaker
2) Use a non-graduated beaker or at least find some way to remove the volume markings
3) Have the diffusion/mixing between phases be more prominent. Currently it is hard to tell that the yellow phase is diffusing into the clear phase (it almost looks like they are just separated by some membrane). I think something like these two images would convey the "transport" aspect more clearly:

![image](https://user-images.githubusercontent.com/23408516/49107483-168efb80-f243-11e8-93e8-46aab31a5ec5.png)

![image](https://user-images.githubusercontent.com/23408516/49107510-23135400-f243-11e8-9930-d7e38b5cec12.png)

**Comment by ejmaginn** [comment]
I agree these are better. I couldn't take a cool photo like above, though I tried. Did you make these images or are they someone else's? The issue is we need to own the copyright.

**Comment by ramess101** [comment]
@ejmaginn 

I just found these online with a quick search of "diffusion beaker." I think we could very easily make our own version of the bottom one though. 

But what was the issue with the real photo? When you dropped some food coloring in a beaker of water did it not diffuse like the picture above?

**Comment by ejmaginn** [comment]
It diffused so rapidly I couldn't get a photo of the cool mixing. The color I used was super water soluble. If somebody has a dye it might work better. Anybody else want to take a shot? I can also ask my colleague to make a cartoon version like the second image.

**Comment by ramess101** [comment]
@ejmaginn 

You could try adding food coloring to something that is much more viscous (but still clear), like olive oil. Then when you add the dyed olive oil to the water it should diffuse a lot more slowly. I can give it a try when I get home.

If your colleague is up for making a cartoon version, that might end up looking better anyways.

**Comment by ejmaginn** [comment]
She's going to make a cartoon - here is something she recently made. 
![crs_cover-art](https://user-images.githubusercontent.com/9609821/49112431-b9a23e00-f260-11e8-82a1-29f5bb6f9067.jpg)

**Comment by ejmaginn** [comment]
What about something like this???
![toc-transport_livecoms_inverted](https://user-images.githubusercontent.com/9609821/49239338-8979ad00-f3d0-11e8-8c8e-dc59d747a1f1.png)

**Comment by ramess101** [comment]
@ejmaginn 

That is a lot better! I am fine sending that unless she is still working on it.

**Comment by ejmaginn** [comment]
OK she's working on one more concept. I'll let you know.

**Comment by ramess101** [comment]
@ejmaginn @drroe @dcarls0n @jrelliottoh 

Ed has finished work on the cover image. I will be submitting this image to LiveCoMS over the weekend, unless someone has strong feelings to modify it or use a different image. 

![image](https://user-images.githubusercontent.com/23408516/49305868-c061c880-f48d-11e8-9f52-2b2e04c59478.png)

**Comment by drroe** [comment]
Looks great!

**Comment by jrelliottoh** [comment]
Looks fine to me.JRE

    On Friday, November 30, 2018, 12:58:03 PM EST, Daniel R. Roe <notifications@github.com> wrote:  
 
 
Looks great!

**Comment by ramess101** [comment]
@ejmaginn @drroe @dcarls0n @jrelliottoh 

OK, there are just a few last things that need to be completed for the manuscript to be published. Here is the email from @mrshirts:

> Got it.  I think there were a few other things in the author instructions that were missing, such as 1) placement in the right place on the GitHub so we know where to get it, and 2) providing the max 30 word lede for the article, and 3) signed contributor license (signed by someone not you, because of NIST policies)  If you can do/provide those things, I think it's set to publish (will do so as soon as we have those).

I will take care of 1). I will write something for 2) but anyone else is welcome to write this or edit my version. @ejmaginn could you complete 3)?

**Comment by ejmaginn** [comment]
Sure. Where is the license? Is it on their website?

**Comment by ramess101** [comment]
@ejmaginn 

I just uploaded the license to the GitHub repository at contributor_license/LiveCoMS_contributor_license.pdf

It is also attached here

[LiveCoMS_contributor_license.pdf](https://github.com/ejmaginn/TransportCheckList/files/2699998/LiveCoMS_contributor_license.pdf)

Here are the LiveCoMS instructions:

> Send a signed copy of the contributor license release form to managing@livecomsjournal.org. As a reminder, this license does not transfer any copyright, but makes it easier for LiveCoMS to publish the article by clarifying that author does indeed have the right to distribute the article open source. See copyright licence section for more information.

I'm not sure if you can electronically sign this form, but either way please send it to the address above and commit the completed form to the contributor_license directory.

Thanks!

**Comment by ejmaginn** [comment]
I emailed the signed license and pushed it to the license directory. 

I like the "lede". Didn't even know what that was.

**Comment by ramess101** [comment]
@ejmaginn 

Great! Michael just confirmed that he received your document.

Haha, I kept thinking it was a typo, like it was supposed to be "led" or "lead." And in fact, it was originally a misspelling of lead but it has now acquired its own meaning. A quick google search can provide loads of interesting information:

![image](https://user-images.githubusercontent.com/23408516/50304282-c889a400-044c-11e9-9667-22dd8e3d7180.png)

**Comment by ramess101** [comment]
@ejmaginn @drroe @dcarls0n @jrelliottoh 

To expedite this process, I have already submitted the lede to @mrshirts. Please express any concerns you have with the lede ASAP so that we can get the ASAP version published ASAP.

**Comment by ramess101** [comment]
@ejmaginn 

Per Michael's request for the initial LiveCoMS release, I am closing this issue
