### ISSUE TITLE
Adding contributors

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#3]
@ejmaginn 

I don't think I can add people since you created the repository. Could you add @jrelliottoh?

**Comment by ramess101** [comment]
@ejmaginn 

Daniel from DIPPR/BYU is willing to contribute to this manuscript. Could you add @dcarls0n?

**Comment by ejmaginn** [comment]
Excellent. Added Daniel…


Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
