### ISSUE TITLE
Viscosity Equations

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#4]
A few variations of the Green-Kubo/Einstein equations are found in the literature, particularly for viscosity. The primary differences are related to what terms of the pressure/stress tensor are included. Some earlier studies appear to have only included Pxy (or Pxz), while more recent studies include at least the three off-diagonal terms and some studies use additional terms.

For example, this is what Mundy et al. (Siepmann) reported in 1996:

![image](https://user-images.githubusercontent.com/23408516/34392435-57295a6a-eb09-11e7-8d0f-9d70d5d9897e.png)

This is what Hess reported in 2002:

![image](https://user-images.githubusercontent.com/23408516/34392511-d0d913a0-eb09-11e7-8215-0ee273683ced.png)

Notice that he still used the Pxz syntax although it appears that he included all three off-diagonal terms. If he did use all three off-diagonal terms, I believe his equations are missing a normalization constant. Although perhaps the constant is lumped into the integrand since he does not explicitly define Pxz.

However, in 1997 Mondello et al. reported using off-diagonal and additional terms:

![image](https://user-images.githubusercontent.com/23408516/34393418-6d50cd7c-eb0f-11e7-8de2-5ef2aef01df9.png)

In fact, Allen and Tildesley discussed averaging the three off-diagonal contributions in their famous text from 1987:

![image](https://user-images.githubusercontent.com/23408516/34394964-666ee0d8-eb1a-11e7-9be3-db9453aa5c70.png)

Chen et al. in 2002 provided a comparison between using just off-diagonal terms and all six terms. They also discussed different methods for weighting the contributions of each term:

![image](https://user-images.githubusercontent.com/23408516/34393283-8e228af0-eb0e-11e7-9239-9e6f1dfd99e2.png)

Chen et al. also demonstrated that using all six terms is very similar to just the off-diagonal terms:

![image](https://user-images.githubusercontent.com/23408516/34393188-eecc48d8-eb0d-11e7-9411-b9105ec51207.png)

Liu et al. (Maginn) provided a useful mini-derivation for the normalization factor of the six term approach:

![image](https://user-images.githubusercontent.com/23408516/34392586-4ad61d6a-eb0a-11e7-8433-ffb64165d79e.png)

So what should we do with these variations? Should we include multiple forms of the Green-Kubo/Einstein equations since they are prevalent in the literature? I think our recommendation should be to use all six terms to improve statistical averaging but I think we should still include the other versions.

**Comment by ramess101** [comment]
@ejmaginn 

Also, I think that there is a typo in Liu et al. Equation 6. I think the p_(alpha,beta) term before tr(p) is the only term that is 1 for alpha=beta and 0 for alpha!=beta. In other words, it likely was supposed to be a different variable, like delta_(alpha,beta).

So I think the equation should be something like:

P_(\alpha,\beta) = \frac{p_{\alpha,\beta}+p_{\beta,\alpha}}{2} - \frac{\delta_{\alpha,\beta}}{3}tr(p)
where p is the stress tensor, $\delta_{\alpha,\beta} = 1 for $\alpha = \beta$ and $\delta_{\alpha,\beta} = 0 for $\alpha \ne \beta$. Otherwise, you have a units issue and the math does not work out. The article that Liu cites as Ref 20 (the 1994 Australian publication by Daivis and Evans) is not very clear but Chen et al. and Mondello et al. (see above) seem to use this expression. 

Furthermore, the factor of 4/3 that arises appears to be a debated issue that is put forward by Borodin et al. but Chen et al. explains why they prefer not using a factor of 4/3 (see above). 

Borodin et al. (also notice that they use the delta_(alpha,beta) notation)

![image](https://user-images.githubusercontent.com/23408516/38895230-af203ffa-424c-11e8-8fe0-13366ea80702.png)

However, if you do not use a factor of 4/3 for the alpha=beta terms, you will not get 10 eta, just 9 eta. So I am still unclear about the weighting factor. But I guess this just demonstrates why we need a document that explains these confusing nuances.

**Comment by ramess101** [comment]
@ejmaginn @dcarls0n 

I did not enter the Einstein viscosity expression correctly in Table 1. I am missing an integral inside of the average. I will fix this after @ejmaginn has pushed his changes. Also, I think we should adopt the notation used by Hess (see above) where we explicitly show that the average is over different initial times (t0). GROMACS provides the same expression:

![image](https://user-images.githubusercontent.com/23408516/39054120-07629d52-446e-11e8-812f-1c521aafa8a0.png)

**Comment by ejmaginn** [comment]
Thanks Richard. I will push my changes Monday and let everyone know. I won’t mess with the equations. 

Ed

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe
