### ISSUE TITLE
Commented PDFs

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#8]
@ejmaginn @drroe @jrelliottoh @dcarls0n 

Please upload a PDF with your suggested changes to the manuscript. After we have reviewed the suggestions, we will decide which ones to implement.

**Comment by ramess101** [comment]
Great, thanks @drroe 

OK, I have attached a PDF with my response to DRR's comments along with my own initiated comments. @ejmaginn  @drroe @dcarls0n @jrelliottoh please add your responses to our comments, either on this PDF or a separate one. Once we have all provided feedback we will start modifying the TEX file.

[EMD_DRR_RAMcomments.pdf](https://github.com/ejmaginn/TransportCheckList/files/1964261/EMD_DRR_RAMcomments.pdf)

**Comment by drroe** [comment]
I'll address minor comments in this Issue to avoid too many versions of the PDF flying around. I'll reproduce the existing comment and any responses to provide context.

> Page 2: "Many codes such as LAMMPS [23] and GROMACS [18] have analysis tools that automatically estimate transport properties..."

> DRR - Can add CPPTRAJ to this list (Roe & Cheatham 2018 JCTC, 10.1021/ct400341p

> ram9 -  was going to include CPPTRAJ, pyTraj, MDTraj, etc. but those tools are strictly for post-simulation analysis. This sentence refers only to simulation packages that also have built-in analysis tools. If we include CPPTRAJ we probably want to modify this sentence to say, "Many analysis tools exist that automatically estimate transport... such as CPPTRAJ, MDTraj, pyTraj, and the built-in analysis tools for LAMMPS and GROMACS."

I think it's fine not to mention all the individual analysis tools, but if we mention LAMMPS and GROMACS we should at least mention Amber and CHARMM as well. Could also mention NAMD but since VMD is really more of a separate analysis tool and not "part" of NAMD this could go either way.

**Comment by drroe** [comment]
> Table 1. Equilibrium molecular dynamics equations.

> DRR - These equations should be generalized to N dimensions, i.e. 2nD = lim(t->inf) MSD/t, etc, since it is not uncommon to want diffusion in 1 or 2 dimensions as well (as is discussed later on in the document).

> ram9 - If we generalize by dimensions we probably need to change the r_i notation so that it is alpha_i, since r denotes a three dimensional vector. Or we could say r_alpha,i to signify r in the alpha direction, since we already use that in our definition for tau.
> What symbol is best for number of dimensions? We already use N and D. I think little n is not very descriptive. What about N_dim?

I think we should change _N_ to _M_ and then use _N_ for number of dimensions

**Comment by drroe** [comment]
> Page 8 - "The second approach is to estimate the infinite system self-diffusivity from a single simulation using an analytic correction factor proposed by Yeh and Hummer [37]."

> DRR - It should be noted that the immersed boundary approach for correcting diffusion for PBC (ref 9, Camley et al) can reproduce Yeh & Hummer's results (discussed in Appendix C that reference) and may be more appropriate for condensed phase anisotropic systems like membranes. There is also a website available that provides corrections to D using this model: https://diffusion.lobos.nih.gov

> ram9 - Do you want to add this to section 5.4 where we discuss membranes as a special topic?

I think that's fine as long as it is mentioned. Let me know if you'd like me to add it directly.

**Comment by ramess101** [comment]
> I'll address minor comments in this Issue to avoid too many versions of the PDF flying around. I'll reproduce the existing comment and any responses to provide context.

Good idea

> I think it's fine not to mention all the individual analysis tools, but if we mention LAMMPS and GROMACS we should at least mention Amber and CHARMM as well. Could also mention NAMD but since VMD is really more of a separate analysis tool and not "part" of NAMD this could go either way.

I agree that we should mention Amber and CHARMM if we are mentioning LAMMPS and GROMACS. Maybe we just want to rewrite this sentence so that we do not need to mention any by name (although we will include a reference for them). We could say something like "Many simulation packages include built-in analysis tools that automatically estimate transport properties, while other post-simulation analysis tools also exist, e.g. Refs [x-y]."

> I think we should change N to M and then use N for number of dimensions

I hesitate to use M for molecules, because that is somewhat inconsistent with using NVE, NVT, NPT ensemble notation. I don't think people want to use MVE, MVT, MPT, or even N_molVE, N_molVT, N_molPT. @ejmaginn @dcarls0n @jrelliottoh Any other options or opinions?

> I think that's fine as long as it is mentioned. Let me know if you'd like me to add it directly.

Yes, you can add it directly. I would wait to push your changes until everyone has had a chance to read through the document though. Maybe on Friday?

**Comment by ejmaginn** [comment]
I will try to get to this by Thursday morning. I am a little swamped today and tomorrow, but I have been following the exchange. One thing I would suggest is to let N = number of molecules. M is confusing, as Rich correctly mentions. People often use "d" for the number of dimensions. I recommend that.

**Comment by ejmaginn** [comment]
Here are my comments / edits.

Ed

**Comment by ramess101** [comment]
@ejmaginn 

I don't see any comments. Did you mean to attach them to your previous post?

**Comment by ejmaginn** [comment]
I thought I did attach but maybe not. I’ll try again in a bit.

Sent from my mobile device

On May 2, 2018, at 5:34 PM, Richard Messerly <notifications@github.com>
wrote:

@ejmaginn <https://github.com/ejmaginn>

I don't see any comments. Did you mean to attach them to your previous post?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ejmaginn/TransportCheckList/issues/8#issuecomment-386128708>,
or mute the thread

**Comment by ejmaginn** [comment]
Can you see them now?

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe

**Comment by ramess101** [comment]
@ejmaginn 

I don't see it anywhere. Are you trying to attach a PDF or upload it to the repository? To attach a PDF you should be able to just drag and drop it. When you click Preview do you see a link to the PDF?

**Comment by ejmaginn** [comment]
I was just trying to send as an email. I uploaded it to the repository now. Hopefully you can now see it.

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe

**Comment by ramess101** [comment]
@ejmaginn 

OK, I have moved your marked PDF to this issue (see attachment), since I don't think we want it in the repository.

[EMD_DRR_RAM_EJM_comments.pdf](https://github.com/ejmaginn/TransportCheckList/files/1971091/EMD_DRR_RAM_EJM_comments.pdf)

**Comment by ejmaginn** [comment]
Thanks. I see. I am a newbie on how this works. Sorry about that!

**Comment by ramess101** [comment]
@ejmaginn 

That is totally fine. This is not standard protocol to begin with. 

Alright, so we have comments from @drroe @ejmaginn and @ramess101.

@dcarls0n and @jrelliottoh are you going to provide some feedback before the end of the week? Specifically, could you opine on the comments raised in the EMD_DRR_RAM_EJM_comments.pdf?

**Comment by dcarls0n** [comment]
Apologies! Classes have started again. I will finish my review and provide any feedback by the end of the day.

**Comment by dcarls0n** [comment]
I added only a few comments (find them in the sections I've listed below):

**Sec 6:** 
-Advocating @ramess101 's Einstein suggestion when replicate simulations are expensive 
**6.1.4:** 
-Quoted the section of the Daivis paper explaining the "os" superscript for clarity
-Raised some clarity concerns regarding the use of Figure 8 in showing the importance of using  all six independent components of the stress tensor vs three terms
**6.2.1 (Model fit to running integral) :** 
-Pointed out a font inconsistency
**6.3.1:** 
-Again commented on the Einstein recommendation to be made

[EMD_DRR_RAM_EJM_DJC_comments_5-3-18.pdf](https://github.com/ejmaginn/TransportCheckList/files/1973170/EMD_DRR_RAM_EJM_DJC_comments_5-3-18.pdf)

**Comment by ramess101** [comment]
Alright, thanks everyone. I think this is all the feedback we are going to get for now. Next Monday I will provide the manuscript to the NIST reviewers. Then, if we get a quick enough turn around, it could be approved for submission by the following Monday (5/14), but no later than 5/21.

@drroe Is it alright if I go through and make all the easy changes right now? Specifically, the changes that I recommended or that were pretty simple fixes. And then I will notify you later today so you can add your changes directly to the LaTex file? I think I should be done in 2-3 hours.

**Comment by drroe** [comment]
Sounds good.

**Comment by ramess101** [comment]
@drroe 

As you probably noticed, this took longer than expected due to a myriad of different issues (mostly not related to this manuscript). However, I have now pushed my changes for the LaTex file and PDF. I have attached my response PDF for all of the comments mentioned previously. You will note that I left you most of the changes that your proposed. Let me know if you have any concerns or questions.

Also, I am still working on fixing the bibliography. Any suggestions are welcome. 

[EMD_v1_5_comments_addressed.pdf](https://github.com/ejmaginn/TransportCheckList/files/1975782/EMD_v1_5_comments_addressed.pdf)

**Comment by ramess101** [comment]
@drroe 

Could you give me a time table for when your changes will be completed? I would like to submit this article to the NIST interval review board as soon as possible, i.e. today or tomorrow. If that is unreasonable for you just let me know, because it is not a big deal to submit the manuscript even if some small changes are made after the fact. I just want to get the process started so we can submit to LiveCoMS by next week. 

Thanks

**Comment by ramess101** [comment]
@drroe 

No problem. Tomorrow would be great. I hope you get to feeling better.

**Comment by drroe** [comment]
My changes have been pushed. Note that I only updated the .tex and .bib files - the software I'm using for PDF generation ran into some issues (maybe because I'm on Linux?), so I didn't try to update that as well.  Let me know if you see any problems or have questions.

**Comment by ramess101** [comment]
@drroe 

Looks great! The PDF and other files are now updated. 

It is now with the NIST reviewers, Arno Laesecke and Alta Fang. We will hear back from them before the end of the week.
