### ISSUE TITLE
NIST Review

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#9]
@ejmaginn @drroe @dcarls0n @jrelliottoh 

I have attached the first NIST reviewer's remarks. All of the changes are minor, but I think two of them are pretty important. First, adding multiple time origins to the checklist and including a bit more discussion about this point. Second, more details about bootstrapping. Specifically, how large the set should be relative to the number of replicates.

[EMD_NIST_reviewer1_comments.pdf](https://github.com/ejmaginn/TransportCheckList/files/1988939/EMD_NIST_reviewer1_comments.pdf)

**Comment by drroe** [comment]
I can't seem to download the PDF - the link appears to just refer to this page. Anyone else seeing that?

**Comment by ramess101** [comment]
@drroe 

Sorry, I did not wait for the download to finish. It should work now.

**Comment by ejmaginn** [comment]
Rich,

I can’t seem to download this - help?

Ed

Edward Maginn
Dorini Family Professor and Department Chair
Department of Chemical and Biomolecular Engineering
University of Notre Dame
Notre Dame, IN 46556 USA
cbe.nd.edu
ed@nd.edu
@ejmaginn
view my papers: https://goo.gl/kgMMBe

**Comment by ramess101** [comment]
@ejmaginn 

Here it is again

[EMD_diffusivity_viscosity_restructured.pdf](https://github.com/ejmaginn/TransportCheckList/files/1990064/EMD_diffusivity_viscosity_restructured.pdf)

**Comment by ramess101** [comment]
@drroe @ejmaginn @jrelliottoh @dcarls0n 

We are still waiting to hear back from the second NIST reviewer. If you have not already done so, please look over the previous reviewers comments. If you object to any of them, make it known soon. I plan on implementing the first reviewers changes tonight.

**Comment by ramess101** [comment]
Here are my responses to each comment.

> It is worthwhile to promote care for uncertainties in computational molecular science as it is routine for experimenters. The Guide to the Expression of Uncertainty in Measurement and related documents as well as the NIST Uncertainty Machine may be helpful to be considered and quoted in this manuscript.

I think we could reference the GUM as well as the LiveCoMS best practices for reporting uncertainty manuscript.

> References [1] and [2] should include URLs to LAMMPS and GROMACS.

OK, 

> The book of Haile should be quoted much more prominently, i. e. earlier in the text, because it is the most pedagogical tutorial of the molecular dynamics method and the best explanation of autocorrelation functions.

This is an important text, but the explanation about transport properties is not very developed or straight forward, in my opinion. And the focus for viscosity is primarily on NEMD. However, I will include it in our list of suggested references to read, specifically, pages 189-192, 485-488,

> The URLs of references [12], [13], and [14] should have tildes ~ instead of the spaces they contain to be functional.

I tried to fix this, but the best I could do was get the tildes ~ to appear without an active link. I read that I can use \%7E instead, but that made the URLs to long to fit on one line.

> Reference [15] is just a two-page note. Is it that significant?

This is Ref [17] now. And yes, I do believe this is a very significant note, albeit brief.

> Line 4 and 5 in the caption of Figure 3: should "length, i. e. trajectory time" not be plural?

Seems reasonable.

> Line 4 in the caption of Figure 6: should "number" not be plural?

Sure.

> Page 14, last line of right column, correct "heurestic" to "heuristic".

Already corrected this.

> Page 17, line 3 of last paragraph in left column: change "as" to "are".

Already corrected this.

> References:
In some citations the DOI and the URL of the DOI are given. Giving only the URL is sufficient and they should be unified to http://doi.org…

I will fix this.

**Comment by ramess101** [comment]
@drroe @ejmaginn @jrelliottoh @dcarls0n 

Let me know if you have any further suggestions in response to these comments. They are all pretty minor. So I will implement them today and submit for the final NIST review by tomorrow. It should be approved by Monday.

**Comment by ejmaginn** [comment]
This all seems reasonable to me. 

Ed

**Comment by ramess101** [comment]
@drroe @ejmaginn @jrelliottoh @dcarls0n 

I just wanted to let everyone know that there was a paperwork mishap at NIST. So the manuscript was not reviewed this past Monday, but it will be reviewed on 5/29 (a Tuesday because there is a federal holiday on Monday). 

Also, I have included some of the syntax changes that were recommended by Ken Kroenlein of TRC. Most likely there will be a few more non-consequential recommendations in the final two editorial reviews. I will let you know if there is anything important enough for us all to discuss.

I expect to submit the manuscript to LiveCoMS on May 30th.

**Comment by ejmaginn** [comment]
@ramess101 thank you - sounds like a good plan.

**Comment by ramess101** [comment]
@drroe @ejmaginn @jrelliottoh @dcarls0n 

Our manuscript has passed the final NIST review. There are a few comments that I wanted to address below.

**Comment by ramess101** [comment]
On page 2 of the manuscript, below Equation 1, we state that "\xi is the perturbation in the Hamiltonian associated with the particular transport property under consideration." However, I believe that statement was orginally written for NEMD methods. EMD does not include any "perturbation in the Hamiltonian." Please correct me if I am misinterpretting this statement. Unless someone else has a better explanation, I am going to replace this statement with "\xi is the mechanical variable associated with the particular transport property under consideration." Does that sound good to everyone?

**Comment by ramess101** [comment]
On page 3, section 4.1.2, paragraph 2, we state that "the uncertainty is inversely proportional to the square root of the number of replicates." Is this uncertainty supposed to be the variance, standard deviation, standard error of the mean, or expanded confidence interval?

**Comment by ejmaginn** [comment]
I think you are right Rich - this is the standard error.
